---
n_experiments: 0 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    atari: &atari True
    log_video: True
    video_path: video
    name: BreakoutNoFrameskip-v4    # PongNoFrameskip-v4, MontezumaRevengeNoFrameskip-v0, BreakoutNoFrameskip-v4
    max_episode_steps: 27000
    seed: 0
agent:
    background_learning: False
    gamma: &gamma 0.99
    algorithm: duel  # double, duel, iqn. or rainbow-iqn, this could be overwritten by the command argument algorithm
    batch_size: 32
    max_steps: 1e7          # maximum training steps
    train_steps: 100000
    eval_steps: 50000

    # model path: model_root_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs  # root path for tensorboard logs
    model_name: baseline

    frame_history_len: 4
    update_freq: 4
    n_steps: 3
    loss_type: huber   # huber or mse
    target_update_freq: 8000    # we count update step, which is 4 times frame steps
    
    Qnets:
        fixup: True
        conv_norm: None     # instance, layer, or None, for convolutional layers
        dense_norm: None    # layer, or None, don't apply instance norm to dense layers
        noisy: True         # use noisy net or scheduled epsilon-greedy
        noisy_sigma: 0.5    # standard deviation for noisy layers
        # args for optimizer
        schedule_lr: True
        learning_rate: 1.e-4
        end_lr: 5.e-5
        clip_norm: 10
        epsilon: 0.0003125
    env_stats:
        times: 1
        stats: [score, score_mean, score_std, score_best, epslen_mean, epslen_std]

# argumennts for prioritized replay
buffer:
    atari: *atari
    type: proportional      # uniform, proportional, or local

    alpha: 0.5
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e6
    min_size: 2e4
    capacity: 1e6

    tb_capacity: 100
