---
n_experiments: 0 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    atari: &atari True
    log_video: True
    video_path: video
    name: BreakoutNoFrameskip-v4    # PongNoFrameskip-v4, BreakoutNoFrameskip-v4, MontezumaRevengeNoFrameskip-v0
    max_episode_steps: 27000        # 108K frames / 4 frames per step
    seed: 0
agent:
    gamma: &gamma 0.99
    algorithm: rainbow-iqn  # double, duel, iqn. or rainbow-iqn, this could be overwritten by the command argument algorithm
    batch_size: 64
    max_steps: 2e8          # maximum training steps

    # model path: model_root_dir/model_name/, two model_names ensure each model saved in an independent folder
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs  # root path for tensorboard logs
    model_name: baseline

    frame_history_len: 4
    update_freq: 4
    n_steps: 3
    loss_type: huber   # huber or mse
    target_update_freq: 8000    # target network updates per target_update_freq online network updates
    
    Qnets:
        conv_norm: instance # instance, layer, or None, for convolutional layers
        dense_norm: layer   # layer, or None, don't apply instance norm to dense layers
        noisy: True         # use noisy net or scheduled epsilon-greedy
        noisy_sigma: 0.5    # standard deviation for noisy layers
        N: 8                # N in paper, num of quantiles for online quantile network
        N_prime: 8          # N' in paper, num of quantiles for target quantile network
        K: 32               # K in paper, num of quantiles for action selection
        delta: 1            # kappa in paper, used in huber loss
        quantile_embedding_dim: 64
        # args for optimizer
        schedule_lr: True
        learning_rate: 1.e-4
        end_lr: 5.e-5
        clip_norm: 10
    env_stats:
        times: 1
        stats: [score, score_mean, score_std, score_best, epslen_mean, epslen_std]

# argumennts for prioritized replay
buffer:
    atari: *atari
    type: proportional      # uniform, proportional, or local

    alpha: 0.5
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e6
    min_size: 5e4
    capacity: 1e6

    tb_capacity: 100
