---
n_experiments: 0 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    atari: &atari True
    video_path: video
    name: PongNoFrameskip-v4    # PongNoFrameskip-v4, MontezumaRevengeNoFrameskip-v0, BreakoutNoFrameskip-v4
    max_episode_steps: 108000
    seed: 0
agent:
    background_learning: False
    gamma: &gamma 0.99
    algorithm: rainbow-iqn  # double, duel, iqn. or rainbow-iqn, this could be overwritten by the command argument algorithm
    batch_size: 32
    prefetches: 5

    # model path: model_root_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs  # root path for tensorboard logs
    model_name: baseline

    frame_history_len: 4
    update_freq: 4
    n_steps: 3
    loss_type: huber   # huber or mse
    target_update_freq: 8000  # we count update step, which is 4 times frame steps
    
    Qnets:
        noisy: True         # use noisy net or scheduled epsilon-greedy
        noisy_sigma: 0.5    # standard deviation for noisy layers
        # args for optimizer
        v_min: -10
        v_max: 10
        n_atoms: 51
        schedule_lr: False
        learning_rate: 6.25e-5
        epsilon: 1.5e-4
        clip_norm: 10
    env_stats:
        times: 1
        stats: [score, avg_score, eps_len, avg_eps_len]

# argumennts for prioritized replay
buffer:
    atari: *atari
    type: proportional      # uniform, proportional, or local

    alpha: 0.5
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e6
    min_size: 8e4
    capacity: 1e6

    tb_capacity: 100
