---
env:
    name: &env_name BipedalWalker-v2    # LunarLanderContinuous-v2
    max_episode_steps: 1000
    seed: 0
agent:
    background_learning: True
    algorithm: apex-td3
    gamma: 0.99
    polyak: 0.995      # moving average rate
    batch_size: 1024
    prefetches: 5

    # model path: model_root_dir/model_name
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs  # root path for tensorboard logs
    model_name: baseline

    n_steps: 3
    policy_delay: 1     # policy will be updated once every policy_delay steps
    n_epochs: 5000
    
    actor:
        n_noisy: 2      # number of noisy layer
        units: [512, 256, 128]
        noisy_sigma: 0.4    # standard deviation for noisy layers
        layernorm: True
        # args for optimizer
        learning_rate: 1e-4
        decay_rate: &decay_rate .95
        decay_steps: &decay_steps 1e4
        
    critic:
        units: [512, 512, 256]
        loss_type: mse   # huber or mse
        layernorm: True
        # args for optimizer
        learning_rate: 3e-4
        decay_rate: *decay_rate
        decay_steps: *decay_steps

    env_stats:
        times: 1
        stats: [score, avg_score, eps_len, avg_eps_len]

# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional

    alpha: 0.4
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 5e4
    min_size: 1e3
    capacity: 1e6

    local_capacity: 100
